import { WordDefinition, Difficulty } from './types';

export const TOTAL_QUESTIONS = 10;

const CHARS_EASY: WordDefinition[] = [
  { "text": "あ", "romaji": "A" }, { "text": "い", "romaji": "I" }, { "text": "う", "romaji": "U" },
  { "text": "え", "romaji": "E" }, { "text": "お", "romaji": "O" }, { "text": "か", "romaji": "KA" },
  { "text": "き", "romaji": "KI" }, { "text": "く", "romaji": "KU" }, { "text": "け", "romaji": "KE" },
  { "text": "こ", "romaji": "KO" }, { "text": "さ", "romaji": "SA" }, { "text": "し", "romaji": "SHI" },
  { "text": "す", "romaji": "SU" }, { "text": "せ", "romaji": "SE" }, { "text": "そ", "romaji": "SO" },
  { "text": "た", "romaji": "TA" }, { "text": "ち", "romaji": "CHI" }, { "text": "つ", "romaji": "TSU" },
  { "text": "て", "romaji": "TE" }, { "text": "と", "romaji": "TO" }, { "text": "な", "romaji": "NA" },
  { "text": "に", "romaji": "NI" }, { "text": "ぬ", "romaji": "NU" }, { "text": "ね", "romaji": "NE" },
  { "text": "の", "romaji": "NO" }, { "text": "は", "romaji": "HA" }, { "text": "ひ", "romaji": "HI" },
  { "text": "ふ", "romaji": "FU" }, { "text": "へ", "romaji": "HE" }, { "text": "ほ", "romaji": "HO" },
  { "text": "ま", "romaji": "MA" }, { "text": "み", "romaji": "MI" }, { "text": "む", "romaji": "MU" },
  { "text": "め", "romaji": "ME" }, { "text": "も", "romaji": "MO" }, { "text": "や", "romaji": "YA" },
  { "text": "ゆ", "romaji": "YU" }, { "text": "よ", "romaji": "YO" }, { "text": "ら", "romaji": "RA" },
  { "text": "り", "romaji": "RI" }, { "text": "る", "romaji": "RU" }, { "text": "れ", "romaji": "RE" },
  { "text": "ろ", "romaji": "RO" }, { "text": "わ", "romaji": "WA" }, { "text": "を", "romaji": "WO" },
  { "text": "ん", "romaji": "NN" }, { "text": "が", "romaji": "GA" }, { "text": "ぎ", "romaji": "GI" },
  { "text": "ぐ", "romaji": "GU" }, { "text": "げ", "romaji": "GE" }, { "text": "ご", "romaji": "GO" },
  { "text": "ざ", "romaji": "ZA" }, { "text": "じ", "romaji": "JI" }, { "text": "ず", "romaji": "ZU" },
  { "text": "ぜ", "romaji": "ZE" }, { "text": "ぞ", "romaji": "ZO" }, { "text": "だ", "romaji": "DA" },
  { "text": "ぢ", "romaji": "DI" }, { "text": "づ", "romaji": "DU" }, { "text": "で", "romaji": "DE" },
  { "text": "ど", "romaji": "DO" }, { "text": "ば", "romaji": "BA" }, { "text": "び", "romaji": "BI" },
  { "text": "ぶ", "romaji": "BU" }, { "text": "べ", "romaji": "BE" }, { "text": "ぼ", "romaji": "BO" },
  { "text": "ぱ", "romaji": "PA" }, { "text": "ぴ", "romaji": "PI" }, { "text": "ぷ", "romaji": "PU" },
  { "text": "ぺ", "romaji": "PE" }, { "text": "ぽ", "romaji": "PO" }, { "text": "きゃ", "romaji": "KYA" },
  { "text": "きゅ", "romaji": "KYU" }, { "text": "きょ", "romaji": "KYO" }, { "text": "しゃ", "romaji": "SHA" },
  { "text": "しゅ", "romaji": "SHU" }, { "text": "しょ", "romaji": "SHO" }, { "text": "ちゃ", "romaji": "CHA" },
  { "text": "ちゅ", "romaji": "CHU" }, { "text": "ちょ", "romaji": "CHO" }, { "text": "にゃ", "romaji": "NYA" },
  { "text": "にゅ", "romaji": "NYU" }, { "text": "にょ", "romaji": "NYO" }, { "text": "ひゃ", "romaji": "HYA" },
  { "text": "ひゅ", "romaji": "HYU" }, { "text": "ひょ", "romaji": "HYO" }, { "text": "みゃ", "romaji": "MYA" },
  { "text": "みゅ", "romaji": "MYU" }, { "text": "みょ", "romaji": "MYO" }, { "text": "りゃ", "romaji": "RYA" },
  { "text": "りゅ", "romaji": "RYU" }, { "text": "りょ", "romaji": "RYO" }, { "text": "ぎゃ", "romaji": "GYA" },
  { "text": "ぎゅ", "romaji": "GYU" }, { "text": "ぎょ", "romaji": "GYO" }, { "text": "じゃ", "romaji": "JA" },
  { "text": "じゅ", "romaji": "JU" }, { "text": "じょ", "romaji": "JO" }
];

const WORDS_NORMAL: WordDefinition[] = [
  { "text": "ねこ", "romaji": "NEKO" }, { "text": "いぬ", "romaji": "INU" }, { "text": "うさぎ", "romaji": "USAGI" },
  { "text": "ぱんだ", "romaji": "PANDA" }, { "text": "らいおん", "romaji": "RAION" }, { "text": "きりん", "romaji": "KIRIN" },
  { "text": "ぞう", "romaji": "ZOU" }, { "text": "さる", "romaji": "SARU" }, { "text": "くま", "romaji": "KUMA" },
  { "text": "こあら", "romaji": "KOARA" }, { "text": "ぺんぎん", "romaji": "PENGIN" }, { "text": "いるか", "romaji": "IRUKA" },
  { "text": "くじら", "romaji": "KUJIRA" }, { "text": "りんご", "romaji": "RINGO" }, { "text": "みかん", "romaji": "MIKAN" },
  { "text": "ぶどう", "romaji": "BUDOU" }, { "text": "いちご", "romaji": "ICHIGO" }, { "text": "めろん", "romaji": "MERON" },
  { "text": "すいか", "romaji": "SUIKA" }, { "text": "ばなな", "romaji": "BANANA" }, { "text": "もも", "romaji": "MOMO" },
  { "text": "さくらんぼ", "romaji": "SAKURANBO" }, { "text": "ぱいなっぷる", "romaji": "PAINAPPURU" },
  { "text": "つくえ", "romaji": "TSUKUE" }, { "text": "いす", "romaji": "ISU" }, { "text": "とけい", "romaji": "TOKEI" },
  { "text": "かばん", "romaji": "KABAN" }, { "text": "えんぴつ", "romaji": "ENPITSU" }, { "text": "けしごむ", "romaji": "KESHIGOMU" },
  { "text": "のーと", "romaji": "NO-TO" }, { "text": "はさみ", "romaji": "HASAMI" }, { "text": "じょうぎ", "romaji": "JOUGI" },
  { "text": "ほっちきす", "romaji": "HOTCHIKISU" }, { "text": "くるま", "romaji": "KURUMA" }, { "text": "でんしゃ", "romaji": "DENSHA" },
  { "text": "ばす", "romaji": "BASU" }, { "text": "たくしー", "romaji": "TAKUSHI-" }, { "text": "じてんしゃ", "romaji": "JITENSHA" },
  { "text": "ひこうき", "romaji": "HIKOUKI" }, { "text": "ふね", "romaji": "FUNE" }, { "text": "しんごう", "romaji": "SHINGOU" },
  { "text": "おうだんほどう", "romaji": "OUDANHODOU" }, { "text": "えき", "romaji": "EKI" }, { "text": "あか", "romaji": "AKA" },
  { "text": "あお", "romaji": "AO" }, { "text": "きいろ", "romaji": "KIIRO" }, { "text": "みどり", "romaji": "MIDORI" },
  { "text": "しろ", "romaji": "SHIRO" }, { "text": "くろ", "romaji": "KURO" }, { "text": "むらさき", "romaji": "MURASAKI" },
  { "text": "ちゃいろ", "romaji": "CHAIRO" }, { "text": "おれんじ", "romaji": "ORENJI" }, { "text": "め", "romaji": "ME" },
  { "text": "みみ", "romaji": "MIMI" }, { "text": "はな", "romaji": "HANA" }, { "text": "くち", "romaji": "KUCHI" },
  { "text": "て", "romaji": "TE" }, { "text": "あし", "romaji": "ASHI" }, { "text": "かお", "romaji": "KAO" },
  { "text": "ゆび", "romaji": "YUBI" }, { "text": "つめ", "romaji": "TSUME" }, { "text": "かみのけ", "romaji": "KAMINOKE" },
  { "text": "ごはん", "romaji": "GOHAN" }, { "text": "ぱん", "romaji": "PAN" }, { "text": "にく", "romaji": "NIKU" },
  { "text": "さかな", "romaji": "SAKANA" }, { "text": "やさい", "romaji": "YASAI" }, { "text": "たまご", "romaji": "TAMAGO" },
  { "text": "ぎゅうにゅう", "romaji": "GYUUNYUU" }, { "text": "かれーらいす", "romaji": "KARE-RAISU" },
  { "text": "おにぎり", "romaji": "ONIGIRI" }, { "text": "うどん", "romaji": "UDON" }, { "text": "そば", "romaji": "SOBA" },
  { "text": "らーめん", "romaji": "RA-MEN" }, { "text": "はる", "romaji": "HARU" }, { "text": "なつ", "romaji": "NATSU" },
  { "text": "あき", "romaji": "AKI" }, { "text": "ふゆ", "romaji": "FUYU" }, { "text": "あめ", "romaji": "AME" },
  { "text": "ゆき", "romaji": "YUKI" }, { "text": "くもり", "romaji": "KUMORI" }, { "text": "はれ", "romaji": "HARE" },
  { "text": "かぜ", "romaji": "KAZE" }, { "text": "たいよう", "romaji": "TAIYOU" }, { "text": "つき", "romaji": "TSUKI" },
  { "text": "ほし", "romaji": "HOSHI" }, { "text": "にじ", "romaji": "NIJI" }, { "text": "いえ", "romaji": "IE" },
  { "text": "まど", "romaji": "MADO" }, { "text": "どあ", "romaji": "DOA" }, { "text": "かぎ", "romaji": "KAGI" },
  { "text": "てれび", "romaji": "TEREBI" }, { "text": "そうじき", "romaji": "SOUJIKI" }, { "text": "せんたくき", "romaji": "SENTAKUKI" },
  { "text": "れいぞうこ", "romaji": "REIZOUKO" }, { "text": "おふろ", "romaji": "OFURO" }, { "text": "といれ", "romaji": "TOIRE" },
  { "text": "がっこう", "romaji": "GAKKOU" }, { "text": "せんせい", "romaji": "SENSEI" }, { "text": "きょうしつ", "romaji": "KYOUSHITSU" },
  { "text": "きゅうしょく", "romaji": "KYUUSHOKU" }, { "text": "てすと", "romaji": "TESUTO" }, { "text": "しゅくだい", "romaji": "SHUKUDAI" }
];

const WORDS_HARD: WordDefinition[] = [
  { "text": "ぱそこん", "romaji": "PASOKON" }, { "text": "すまーとふぉん", "romaji": "SUMA-TOFON" }, { "text": "たぶれっと", "romaji": "TABURETTO" },
  { "text": "きーぼーど", "romaji": "KI-BO-DO" }, { "text": "まうす", "romaji": "MAUSU" }, { "text": "もにたー", "romaji": "MONITA-" },
  { "text": "ぷりんたー", "romaji": "PURINTA-" }, { "text": "いんたーねっと", "romaji": "INTA-NETTO" }, { "text": "わいふぁい", "romaji": "WAIFAI" },
  { "text": "ぶるーとぅーす", "romaji": "BURU-TU-SU" }, { "text": "あぷりけーしょん", "romaji": "APURIKE-SHON" },
  { "text": "だうんろーど", "romaji": "DAUNRO-DO" }, { "text": "あっぷろーど", "romaji": "APPURO-DO" }, { "text": "いんすとーる", "romaji": "INSUTO-RU" },
  { "text": "あっぷでーと", "romaji": "APPUDE-TO" }, { "text": "ろぐいん", "romaji": "ROGUIN" }, { "text": "ろぐあうと", "romaji": "ROGUAUTO" },
  { "text": "ぱすわーど", "romaji": "PASUWA-DO" }, { "text": "あかうんと", "romaji": "AKAUNTO" }, { "text": "ぷろぐらみんぐ", "romaji": "PUROGRAMINGU" },
  { "text": "えんじにあ", "romaji": "ENJINIA" }, { "text": "でざいなー", "romaji": "DEZAINA-" }, { "text": "でーたべーす", "romaji": "DE-TABE-SU" },
  { "text": "さーばー", "romaji": "SA-BA-" }, { "text": "ねっとわーく", "romaji": "NETTOWA-KU" }, { "text": "せきゅりてぃ", "romaji": "SEKYURITI" },
  { "text": "ういるす", "romaji": "UIRUSU" }, { "text": "ばっくあっぷ", "romaji": "BAKKUAPPU" }, { "text": "あにめーしょん", "romaji": "ANIME-SHON" },
  { "text": "きゃらくたー", "romaji": "KYARAKUTA-" }, { "text": "まんが", "romaji": "MANGA" }, { "text": "げーむ", "romaji": "GE-MU" },
  { "text": "こんとろーらー", "romaji": "KONTORO-RA-" }, { "text": "あくしょん", "romaji": "AKUSHON" }, { "text": "ろーるぷれえいんぐ", "romaji": "RO-RUPUREEINGU" },
  { "text": "おんらいん", "romaji": "ONRAIN" }, { "text": "ぴかちゅう", "romaji": "PIKACHUU" }, { "text": "どらえもん", "romaji": "DORAEMON" },
  { "text": "あんぱんまん", "romaji": "ANPANMAN" }, { "text": "そんごくう", "romaji": "SONGOKUU" }, { "text": "るふぃ", "romaji": "RUFII" },
  { "text": "えどがわこなん", "romaji": "EDOGAWAKONAN" }, { "text": "のびた", "romaji": "NOBITA" }, { "text": "かめはめは", "romaji": "KAMEHAMEHA" },
  { "text": "らせんがん", "romaji": "RASENGAN" }, { "text": "りょういきてんかい", "romaji": "RYOUIKITENKAI" }, { "text": "こきゅう", "romaji": "KOKYUU" },
  { "text": "にちりんとう", "romaji": "NICHIRINTOU" }, { "text": "あくまのみ", "romaji": "AKUMANOMI" }, { "text": "すーぱーさいやじん", "romaji": "SU-PA-SAIYAJIN" },
  { "text": "ゆーちゅーばー", "romaji": "YU-CHU-BA-" }, { "text": "いんすたぐらむ", "romaji": "INSUTAGURAMU" }, { "text": "ついったー", "romaji": "TSUITTA-" },
  { "text": "らいん", "romaji": "RAIN" }, { "text": "はっしゅたぐ", "romaji": "HASSHUTAGU" }, { "text": "いんふるえんさー", "romaji": "INFURUENSA-" },
  { "text": "ばず", "romaji": "BAZU" }, { "text": "どうがはいしん", "romaji": "DOUGAHAISHIN" }, { "text": "ちょこれーと", "romaji": "CHOKORE-TO" },
  { "text": "あいすくりーむ", "romaji": "AISUKURI-MU" }, { "text": "はんばーがー", "romaji": "HANBA-GA-" }, { "text": "さんどいっち", "romaji": "SANDOICCHI" },
  { "text": "すぱげってぃ", "romaji": "SUPAGETTI" }, { "text": "おむらいす", "romaji": "OMURAISU" }, { "text": "えびふらい", "romaji": "EBIFURAI" },
  { "text": "すてーき", "romaji": "SUTE-KI" }, { "text": "ぴざ", "romaji": "PIZA" }, { "text": "ほっとけーき", "romaji": "HOTTOKE-KI" },
  { "text": "すぽーつ", "romaji": "SUPO-TSU" }, { "text": "さっかー", "romaji": "SAKKA-" }, { "text": "やきゅう", "romaji": "YAKYUU" },
  { "text": "ばすけっとぼーる", "romaji": "BASUKETTOBO-RU" }, { "text": "てにす", "romaji": "TENISU" }, { "text": "ばれーぼーる", "romaji": "BARE-BO-RU" },
  { "text": "すいえい", "romaji": "SUIEI" }, { "text": "おりんぴっく", "romaji": "ORINPIKKU" }, { "text": "すかいつりー", "romaji": "SUKAITSURI-" },
  { "text": "ゆうえんち", "romaji": "YUUENCHI" }, { "text": "どうぶつえん", "romaji": "DOUBUTSUEN" }, { "text": "すいぞくかん", "romaji": "SUIZOKUKAN" },
  { "text": "えいがかん", "romaji": "EIGAKAN" }, { "text": "びじゅつかん", "romaji": "BIJUTSUKAN" }, { "text": "としょかん", "romaji": "TOSHOKAN" },
  { "text": "こんびに", "romaji": "KONBINI" }, { "text": "すーぱーまーけっと", "romaji": "SU-PA-MA-KETTO" }
];

const WORDS_MASTER: WordDefinition[] = [
  { "text": "いそがばまわれ", "romaji": "ISOGABAMAWARE" }, { "text": "いっせきにちょう", "romaji": "ISSEKINICHOU" },
  { "text": "いしんでんしん", "romaji": "ISHINDENSHIN" }, { "text": "いちごいちえ", "romaji": "ICHIGOICHIE" },
  { "text": "きどあいらく", "romaji": "KIDOAIRAKU" }, { "text": "しんしゅつきぼつ", "romaji": "SHINSHUTSUKIBOTSU" },
  { "text": "ぜったいぜつめい", "romaji": "ZETTAIZETSUMEI" }, { "text": "ゆだんたいてき", "romaji": "YUDANTAITEKI" },
  { "text": "りんきおうへん", "romaji": "RINKIOUHEN" }, { "text": "ごりむちゅう", "romaji": "GORIMUCHUU" },
  { "text": "しめんそか", "romaji": "SHIMENSOKA" }, { "text": "たいきばんせい", "romaji": "TAIKIBANSEI" },
  { "text": "じがじさん", "romaji": "JIGAJISAN" }, { "text": "こうじつけ", "romaji": "KOUJITSUKE" },
  { "text": "じごうじとく", "romaji": "JIGOUJITOKU" }, { "text": "たんとちょくにゅう", "romaji": "TANTOCHOKUNYUU" },
  { "text": "むがむちゅう", "romaji": "MUGAMUCHUU" }, { "text": "ゆいいつむに", "romaji": "YUIIITSUMUNI" },
  { "text": "りょうさいけんぼ", "romaji": "RYOUSAIKENBO" }, { "text": "ろうにゃくなんにょ", "romaji": "ROUNYAKUNANNYO" },
  { "text": "わようせっちゅう", "romaji": "WAYOUSECCHUU" }, { "text": "あいまいもこ", "romaji": "AIMAIMOKO" },
  { "text": "いきとうごう", "romaji": "IKITOUGOU" }, { "text": "うおうさおう", "romaji": "UOUSAOU" },
  { "text": "おんこちしん", "romaji": "ONKOCHISHIN" }, { "text": "がりょうてんせい", "romaji": "GARYOUTENSEI" },
  { "text": "きしかいせい", "romaji": "KISHIKAISEI" }, { "text": "くうぜんぜつご", "romaji": "KUUZENZETSUGO" },
  { "text": "こうめいせいだい", "romaji": "KOUMEISEIDAI" }, { "text": "さいしょくけんび", "romaji": "SAISHOKUKENBI" },
  { "text": "しちてんはっき", "romaji": "SHICHITENHAKKI" }, { "text": "じゅうにんといろ", "romaji": "JUUNINTOIRO" },
  { "text": "せいせいどうどう", "romaji": "SEISEIDOUDOU" }, { "text": "ぜんじんみとう", "romaji": "ZENJINMITOU" },
  { "text": "だいどうしょうい", "romaji": "DAIDOUSHOUI" }, { "text": "てんしんらんまん", "romaji": "TENSHINRANMAN" },
  { "text": "ににんさんきゃく", "romaji": "NININSANKYAKU" }, { "text": "はくしかっさい", "romaji": "HAKUSHIKASSAI" },
  { "text": "はんめんきょうし", "romaji": "HANMENKYOUSHII" }, { "text": "ひんこうほうせい", "romaji": "HINKOUHOUSEI" },
  { "text": "ふとうふくつ", "romaji": "FUTOUFUKUTSU" }, { "text": "ほんまつてんとう", "romaji": "HONMATSUTENTOU" },
  { "text": "みっかぼうず", "romaji": "MIKKABOUZU" }, { "text": "ゆがどくそん", "romaji": "YUGADOKUSON" },
  { "text": "よういしゅうとう", "romaji": "YOUISHUUTOU" }, { "text": "りがいかんけい", "romaji": "RIGAIKANKEI" },
  { "text": "ねこにこばん", "romaji": "NEKONIKOBAN" }, { "text": "さるもきからおちる", "romaji": "SARUMOKIKARAOCHIRU" },
  { "text": "ちりもつもれば", "romaji": "CHIRIMOTSUMOREBA" }, { "text": "いぬもあるけば", "romaji": "INUMOARUKEBA" },
  { "text": "えびでたいをつる", "romaji": "EBIDETAIWOTSURU" }, { "text": "おににかなぼう", "romaji": "ONINIKANABOU" },
  { "text": "かっぱの川流れ", "romaji": "KAPPANOKAWANAGARE" }, { "text": "かわいいこには", "romaji": "KAWAIIKONIWA" },
  { "text": "きいてごくらく", "romaji": "KIITEGOKURAKU" }, { "text": "くさいものにふた", "romaji": "KUSAIMONONIFUTA" },
  { "text": "こうかいさきにたたず", "romaji": "KOUKAISAKINITATAZU" }, { "text": "ごうにいっては", "romaji": "GOUNIIHTEWA" },
  { "text": "しらぬがほとけ", "romaji": "SHIRANUGAHOTOKE" }, { "text": "すずめのなみだ", "romaji": "SUZUMENONAMIDA" },
  { "text": "せにはらはかえられぬ", "romaji": "SENIHARAHAKAERARENU" }, { "text": "ぜんはいそげ", "romaji": "ZENHAISOGE" },
  { "text": "たなからぼたもち", "romaji": "TANAKARABOTAMOCHI" }, { "text": "つきとすっぽん", "romaji": "TSUKITOSUPPON" },
  { "text": "でるくいはうたれる", "romaji": "DERUKUIHAUTARERU" }, { "text": "とうだもとくらし", "romaji": "TOUDAMOTOKURASHI" },
  { "text": "となりのしばふ", "romaji": "TONARINOSHIBAFU" }, { "text": "どんぐりのせいくらべ", "romaji": "DONGURINOSEIKURABE" },
  { "text": "ながいものにはまかれろ", "romaji": "NAGAIMONONIHAMAKARERO" }, { "text": "ななころびやおき", "romaji": "NANAKOROBIYAOKI" },
  { "text": "ぬかにくぎ", "romaji": "NUKANIKUGI" }, { "text": "ねみみにみず", "romaji": "NEMIMINIMIZU" },
  { "text": "のれんにうでおし", "romaji": "NORENNIUDEOSHI" }, { "text": "はやおきはさんもんの", "romaji": "HAYAOKIHASANMONNO" },
  { "text": "ひひと、ひとのふりみて", "romaji": "HITONOFURIMITE" }, { "text": "ひょうたんからこま", "romaji": "HYOUTANKARAKOMA" },
  { "text": "まけるがかち", "romaji": "MAKERUGAKACHI" }, { "text": "やぶからぼう", "romaji": "YABUKARABOU" },
  { "text": "らくあればくあり", "romaji": "RAKUAREBAKUARI" }, { "text": "りょうやくはくちに", "romaji": "RYOUYAKUHAKUCHINI" },
  { "text": "るいはともをよぶ", "romaji": "RUIHATOMOWOYOBU" }, { "text": "わらうかどには", "romaji": "WARAUKADONIWA" },
  { "text": "あきらめたらそこで", "romaji": "AKIRAMETARASOKODE" }, { "text": "しんじつはいつも", "romaji": "SHINJITSUWAITSUMO" },
  { "text": "にげちゃだめだ", "romaji": "NIGECHADAMEDA" }, { "text": "まだあわてる", "romaji": "MADAAWATERU" },
  { "text": "おまえはもう", "romaji": "OMAEWAMOU" }, { "text": "かみにいのりを", "romaji": "KAMINIINORIWO" },
  { "text": "たいむいずまねー", "romaji": "TAIMUIZUMANE-" }, { "text": "げーむせっと", "romaji": "GE-MUSETTO" },
  { "text": "こんてぃにゅー", "romaji": "KONTINYU-" }, { "text": "みっしょん", "romaji": "MISSHON" },
  { "text": "こんぷりーと", "romaji": "KONPURI-TO" }, { "text": "ばるす", "romaji": "BARUSU" },
  { "text": "めがみえます", "romaji": "MEGAMIEMASU" }, { "text": "ひとがごみのようだ", "romaji": "HITOGAGOMINOYOUDA" },
  { "text": "だがことわる", "romaji": "DAGAKOTOWARU" }, { "text": "やれやれだぜ", "romaji": "YAREYAREDAZE" },
  { "text": "ひんじゃくひんじゃく", "romaji": "HINJAKUHINJAKU" }, { "text": "おらおらおら", "romaji": "ORAORAORA" },
  { "text": "むだむだむだ", "romaji": "MUDAMUDAMUDA" }, { "text": "ざわーるど", "romaji": "ZAWA-RUDO" },
  { "text": "すたーぷらちな", "romaji": "SUTA-PURACHINA" }, { "text": "けいかくどおり", "romaji": "KEIKAKUDOORI" },
  { "text": "ぎりぎりあうと", "romaji": "GIRIGIRIAUTO" }, { "text": "ざわざわ", "romaji": "ZAWAZAWA" },
  { "text": "ばいおはざーど", "romaji": "BAIOHAZA-DO" }, { "text": "もんはん", "romaji": "MONHAN" },
  { "text": "ひとかりいこうぜ", "romaji": "HITOKARIIKOUZE" }, { "text": "すまぶら", "romaji": "SUMABURA" },
  { "text": "まりおかーと", "romaji": "MARIOKA-TO" }, { "text": "どうぶつのもり", "romaji": "DOUBUTSUNOMORI" },
  { "text": "あぺっくす", "romaji": "APEKKUSU" }, { "text": "ばろらんと", "romaji": "BARORANTO" },
  { "text": "ふぉーとないと", "romaji": "FO-TONAITO" }, { "text": "まいくら", "romaji": "MAIKURA" },
  { "text": "りーぐおぶれじぇんど", "romaji": "RI-GUOBUREJENDO" }, { "text": "すとりーとふぁいたー", "romaji": "SUTORI-TOWAITA-" },
  { "text": "ふぁいなりふぁんたじー", "romaji": "FAINARUFANTAJI-" }, { "text": "どらごんくえすと", "romaji": "DORAGONKUESUTO" },
  { "text": "ゆうしゃ", "romaji": "YUUSHA" }, { "text": "まおう", "romaji": "MAOU" },
  { "text": "すらいむ", "romaji": "SURAIME" }, { "text": "かいしんのいちげき", "romaji": "KAISHINNOICHIGEKI" },
  { "text": "いのちだいじに", "romaji": "INOCHIDAIJINI" }, { "text": "がんがんいこうぜ", "romaji": "GANGANIKOUZE" },
  { "text": "れべるあっぷ", "romaji": "REBERUAPPU" }, { "text": "すてーたす", "romaji": "SUTE-TASU" },
  { "text": "くえすと", "romaji": "KUESUTO" }, { "text": "だんじょん", "romaji": "DANJON" },
  { "text": "ぱーてぃ", "romaji": "PA-TI" }, { "text": "ぎるど", "romaji": "GIRUDO" },
  { "text": "のら", "romaji": "NORA" }, { "text": "りせまら", "romaji": "RISEMARA" },
  { "text": "かきん", "romaji": "KAKIN" }, { "text": "はいかきん", "romaji": "HAIKAKIN" },
  { "text": "むかきん", "romaji": "MUKAKIN" }, { "text": "ろぐいんぼーなす", "romaji": "ROGUINBO-NASU" },
  { "text": "めんてなんす", "romaji": "MENTENANSU" }, { "text": "さーばーだうん", "romaji": "SA-BA-DAUN" },
  { "text": "ばぐ", "romaji": "BAGU" }, { "text": "らぐい", "romaji": "RAGUI" },
  { "text": "ちーと", "romaji": "CHI-TO" }, { "text": "あかばん", "romaji": "AKABAN" },
  { "text": "ねたばれ", "romaji": "NETABARE" }, { "text": "ふらぐかいしゅう", "romaji": "FURAGUKAISHUU" },
  { "text": "しぼうふらぐ", "romaji": "SHIBOUFURAGU" }, { "text": "いせかい", "romaji": "ISEKAI" },
  { "text": "てんせい", "romaji": "TENSEI" }, { "text": "おれつえー", "romaji": "ORETSUE-" },
  { "text": "はーレム", "romaji": "HA-REMU" }, { "text": "ひろいん", "romaji": "HIROIN" },
  { "text": "つんでれ", "romaji": "TSUNDERE" }, { "text": "やんでれ", "romaji": "YANDERE" },
  { "text": "くうでれ", "romaji": "KUUDERE" }, { "text": "おさななじみ", "romaji": "OSANANAJIMI" },
  { "text": "いもうと", "romaji": "IMOUTO" }, { "text": "ねこみみ", "romaji": "NEKOMIMI" },
  { "text": "めいど", "romaji": "MEIDO" }, { "text": "しつじ", "romaji": "SHITSUJI" },
  { "text": "せいゆう", "romaji": "SEIYUU" }, { "text": "あいどる", "romaji": "AIDORU" },
  { "text": "おたく", "romaji": "OTAKU" }, { "text": "どうじんし", "romaji": "DOUJINSHI" },
  { "text": "こすぷれ", "romaji": "KOSUPURE" }, { "text": "こみけ", "romaji": "KOMIKE" },
  { "text": "せいちじゅんれい", "romaji": "SEICHIJUNREI" }, { "text": "にこにこどうが", "romaji": "NIKONIKODOUGA" },
  { "text": "はつねみく", "romaji": "HATSUNEMIKU" }, { "text": "せんぼんざくら", "romaji": "SENBONZAKURA" },
  { "text": "ぶいちゅーばー", "romaji": "BUICHU-BA-" }, { "text": "すーぱーちゃっと", "romaji": "SU-PA-CHATTO" },
  { "text": "きりぬき", "romaji": "KIRINUKI" }, { "text": "ゆっくりしていってね", "romaji": "YAKKURISHITEITTENE" },
  { "text": "してやんよ", "romaji": "SHITEYANYO" }, { "text": "おまえがいな", "romaji": "OMAEGAIUNA" },
  { "text": "こうめいのわな", "romaji": "KOUMEINOWANA" }, { "text": "おわこん", "romaji": "OWAKON" },
  { "text": "くろれきし", "romaji": "KUROREKISHI" }, { "text": "かみげー", "romaji": "KAMIGE-" },
  { "text": "くそげー", "romaji": "KUSOGE-" }, { "text": "むりげー", "romaji": "MURIGE-" },
  { "text": "あーるてぃーえー", "romaji": "A-RUTI-E-" }, { "text": "かんこれ", "romaji": "KANKORE" },
  { "text": "とうほう", "romaji": "TOUHOU" }, { "text": "うまむすめ", "romaji": "UMAMUSUME" },
  { "text": "らぶらいぶ", "romaji": "RABURAIBU" }, { "text": "ふぇいと", "romaji": "FEITO" },
  { "text": "えゔぁ", "romaji": "EVA" }, { "text": "しと", "romaji": "SHITO" },
  { "text": "えーてぃーふぃーるど", "romaji": "E-TI-FI-RUDO" }, { "text": "にゅーたいぷ", "romaji": "NYU-TAIPU" },
  { "text": "ざく", "romaji": "ZAKU" }, { "text": "さんばい", "romaji": "SANBAI" },
  { "text": "あえていおう", "romaji": "AETEIOU" }, { "text": "ぼうやだからさ", "romaji": "BOUYADAKARASA" },
  { "text": "まかんこうさっぽう", "romaji": "MAKAKKOUSAPPOU" }, { "text": "きえんざん", "romaji": "KIENZAN" },
  { "text": "げんきだま", "romaji": "GENKIDAMA" }, { "text": "せんず", "romaji": "SENZU" },
  { "text": "ごむごむの", "romaji": "GOMUGOMUNO" }, { "text": "かいぞくおうに", "romaji": "KAIZOKUOUNI" },
  { "text": "ざんぱくとう", "romaji": "ZANPAKUTOU" }, { "text": "ばんかい", "romaji": "BANKAI" },
  { "text": "ねんのうりょく", "romaji": "NENNOURYOKU" }, { "text": "はんたー", "romaji": "HANTA-" },
  { "text": "れんきんじゅつ", "romaji": "RENKINJUTSU" }, { "text": "とうかせん", "romaji": "TOUKASEN" },
  { "text": "ちぇんそーまん", "romaji": "CHENSO-MAN" }, { "text": "すぱいふぁみりー", "romaji": "SUPAIFAMIRI-" },
  { "text": "わくわく", "romaji": "WAKUWAKU" }, { "text": "よゆう", "romaji": "YOYUU" },
  { "text": "ちょうしにのるな", "romaji": "CHOUSHININORUNA" }, { "text": "ぜつぼうした", "romaji": "ZETSUBOUHITA" },
  { "text": "うぃざーど", "romaji": "WIZA-DO" }, { "text": "ひーらー", "romaji": "HI-RA-" },
  { "text": "たんく", "romaji": "TANKU" }, { "text": "でぃーぴーえす", "romaji": "DI-PI-ESU" },
  { "text": "ばふ", "romaji": "BAFU" }, { "text": "でばふ", "romaji": "DEBAFU" },
  { "text": "しかのこのこのここしたんたん", "romaji": "sikanokononokokositantann" },
  { "text": "きびしいってききかんもったほう", "romaji": "kibisii-ttekikikannmottahou" },
  { "text": "ききかんもったほうがいい", "romaji": "kikikannmottahougaii" },
  { "text": "それがーちゃーほんまごめんやで", "romaji": "sorega-tya-honnmagomennyade" },
  { "text": "ないたーあげみざわあざまる", "romaji": "naita-agemizawaazamaru" },
  { "text": "あざまるすいさん", "romaji": "azamarusuisann" },
  { "text": "すいちゃんはきょうもかわいい", "romaji": "suityannhakyoumokawaii" },
  { "text": "おまえのはかはここになる", "romaji": "omaenohakahakokoninaru" },
  { "text": "まほうはさがしているときが", "romaji": "mahouhasagasiteirutokiga" },
  { "text": "さいじょうきゅうにかわいいの", "romaji": "saijoukyuunikawaii-no" },
  { "text": "ふろきゃんせるかいわい", "romaji": "furokyannserukaiwai" },
  { "text": "いとまきまきいとまきまき", "romaji": "itomakimakiitomakimaki" },
  { "text": "きょうびじゅいいじゃん", "romaji": "kyoubijuiijan" },
  { "text": "きみとのきょりごせんち", "romaji": "kimitonokyorigosenn-ti" },
  { "text": "うちらこるかわいすぎる", "romaji": "utirakorukawaisugiru" },
  { "text": "ちぴちぴちゃぱちゃぱ", "romaji": "tipitipityapatyapa" },
  { "text": "どきゅうのりとらい", "romaji": "dokyuunoritorai" },
  { "text": "なーぜなーぜ", "romaji": "na-zena-ze" },
  { "text": "きまずぃーぽーず", "romaji": "kimazu-i-po-zu" },
  { "text": "へいせいれとろぶーむ", "romaji": "heiseiretorobu-mu" },
  { "text": "むかつきしきぶ", "romaji": "mukatikisikibu" },
  { "text": "ちょうちるならっぱー", "romaji": "tyoutirunarappa-" },
  { "text": "あざらしようちえん", "romaji": "azarasiyoutienn" },
  { "text": "すきなそうざいはっぴょう", "romaji": "sukinasouzaihappyou" },
  { "text": "しあわせならおーけーです", "romaji": "siawasenarao-ke-desu" },
  { "text": "めぞまらいざー", "romaji": "mezomaraiza-" },
  { "text": "ぷにるはかわいいすらいむ", "romaji": "puniruhakawaii-suraimu" },
  { "text": "うどーなつたべたい", "romaji": "udo-natutabetai" },
  { "text": "ねこみーむおもしろすぎ", "romaji": "nekomi-muomosirosugiru" },
  { "text": "びよんせからまもる", "romaji": "biyonnsekaramamoru" },
  { "text": "だいじょうぶぼくさいきょう", "romaji": "daijoububokusaikyou" },
  { "text": "いきざまでこうかいしたくない", "romaji": "ikizamadekoukaisitakunai" },
  { "text": "おまえはじゅんあいだよ", "romaji": "omaehajunnaidayo" },
  { "text": "てんじょうてんげゆいがどくそん", "romaji": "tennjoutenngeyuyigadokusonn" },
  { "text": "しゃみこがわるいんだよ", "romaji": "syamikogawaruinndayo" },
  { "text": "うそはとびきりのあい", "romaji": "usowatobikirinoai" },
  { "text": "きみはむてきのあいどる", "romaji": "kimihamutekinoaidoru" },
  { "text": "ばんかいせんぼんざくら", "romaji": "bannkaisennoonnzakura" },
  { "text": "おまえはもうしんでいる", "romaji": "omaewamousindeiru" },
  { "text": "ばるすとおなえした", "romaji": "barusutoonaesita" },
  { "text": "あきらめたらそこでしりょう", "romaji": "akirametarasokodesiryou" },
  { "text": "だがことわる", "romaji": "dagakotowaru" },
  { "text": "こんかいのげーむおわり", "romaji": "konnkainoge-muowari" },
  { "text": "しんぶんしをよむ", "romaji": "sinnbunnssiwoyomu" },
  { "text": "たけやぶやけた", "romaji": "takeyabuyaketa" },
  { "text": "すもももももももものうち", "romaji": "sumomomomomomomomonouti" },
  { "text": "なまむぎなまごめなまたまご", "romaji": "namamuginamagomenamatamago" },
  { "text": "ふるさとのやまはありがたき", "romaji": "furusatonoyamawaarigataki" },
  { "text": "じゅげむじゅげむごこうの", "romaji": "jugemujugemugokouno" },
  { "text": "おーまいがーなじけん", "romaji": "o-maiga-najikenn" },
  { "text": "まじまじまじんがー", "romaji": "majimajimajinnga-" },
  { "text": "ほんまにあかんて", "romaji": "honmaniakannte" },
  { "text": "それなそれなそれな", "romaji": "sorenasorenasorena" },
  { "text": "わらわらわらわらわら", "romaji": "warawarawarawarawara" },
  { "text": "めろめろめろいちゃむ", "romaji": "meromeromeroityamu" },
  { "text": "どかうつおうてんちゃんねる", "romaji": "dokauutuoutenntyannneru" },
  { "text": "しぬーしぬーしぬー", "romaji": "sinu-sinu-sinu-" },
  { "text": "ほんまねーわかんね", "romaji": "honmanne-wakannne" },
  { "text": "かりかりうめしかかたん", "romaji": "karikariumesikakatan" },
  { "text": "しぐまぼーいかっこいい", "romaji": "sigumabo-ikakkoii" },
  { "text": "おはこんこん", "romaji": "ohakonnkonn" },
  { "text": "おつるんちょま", "romaji": "oturunntyoma" },
  { "text": "きんちょうしてしゃべれない", "romaji": "kinntyousitesyaberenai" },
  { "text": "みらいはいまのえんちょうせん", "romaji": "miraiwaimaonoenntyousenn" },
  { "text": "へいぼんがいちばんいい", "romaji": "heibonngaityibannii" },
  { "text": "よしはおおいといて", "romaji": "yosiwaooitoite" },
  { "text": "あきらめなければむくわれる", "romaji": "akiramenakerebamukuwareru" },
  { "text": "おれのなまえはせらふ", "romaji": "orenonamaewaserafu" },
  { "text": "ぼるたくしょーーーん", "romaji": "borutakusyo----nn" },
  { "text": "おまえらさいこうのひーろー", "romaji": "omaerasaikounohi-ro-" },
  { "text": "いっかいせきいぇーーーい", "romaji": "ikkaisekiyee---i" },
  { "text": "にかいせきいぇーーーい", "romaji": "nikaisekiyee---i" },
  { "text": "さんがいせきいぇーーーい", "romaji": "sangaisekiyee---i" },
  { "text": "がちでしぬかとおもった", "romaji": "gatidesinukatoomotta" },
  { "text": "きょうはさいこうのひ", "romaji": "kyouwasaikounohi" },
  { "text": "あしたしぬかもしれない", "romaji": "asitasinukamosirenai" },
  { "text": "よしよりもひとのよさ", "romaji": "yosiyorimohitonoyosa" },
  { "text": "てきどにち力をぬく", "romaji": "tekidonitikarawonuku" },
  { "text": "いきてればもんだいない", "romaji": "ikiterebamonndainai" },
  { "text": "おいしいものたべてふとる", "romaji": "oisimonotabetefutoru" },
  { "text": "はろーゆーちゅーぶ", "romaji": "haro-yu-tyu-bu" },
  { "text": "ひかきんちるどれん", "romaji": "hikakintirudorenn" },
  { "text": "きゅうびのちゃくら", "romaji": "kyuubinityakura" },
  { "text": "どうもみなさんこんにちは", "romaji": "doumominasannkonnnitiwa" },
  { "text": "とうだいせいくいずおう", "romaji": "toudaiseikuizuou" },
  { "text": "くいずのっくへんしゅうちょ", "romaji": "kuizunokkuhennsyuutyo" },
  { "text": "いざわたくしです", "romaji": "izawatakusidesu" },
  { "text": "はいどうもー", "romaji": "haidoumo-" },
  { "text": "あんでっどあんでっど", "romaji": "andeddandoddo" },
  { "text": "じょーじめんずこーち", "romaji": "jo-jimennzuko-ti" },
  { "text": "おぢがしつこい", "romaji": "odigasitukoi" },
  { "text": "へびかげんしょう", "romaji": "hebikagennsyou" },
  { "text": "かえるかげんしょう", "romaji": "kaerukagennsyou" },
  { "text": "まじでむりぽよ", "romaji": "majidemuripoyo" },
  { "text": "なーぜなーぜだよ", "romaji": "na-zena-zedayo" },
  { "text": "ぎりぎりはっぴー", "romaji": "girigirihappi-" },
  { "text": "きょうばいとだりい", "romaji": "kyoubaitodarii" },
  { "text": "ねっこがあるいてます", "romaji": "nekkogaaruitemasu" },
  { "text": "かちかちこおったはが", "romaji": "katikatikoottahaga" },
  { "text": "うちらころかわいすぎ", "romaji": "utirakorokawaisugi" },
  { "text": "しらんけどなー", "romaji": "sirannkedona-" },
  { "text": "ここわろあだっけ", "romaji": "kokowaroadakke" },
  { "text": "びざがないといだされた", "romaji": "bizagannaitoidasareta" },
  { "text": "かなしくてないていた", "romaji": "kanasikutenaiteita" },
  { "text": "さいじょうきゅうにかわいい", "romaji": "saijoukyuunikawaii" },
  { "text": "おとめのごふくしゅう", "romaji": "otomenogofukusyuu" },
  { "text": "おかねかせぐおれたち", "romaji": "okanekaseguoretati" },
  { "text": "わたしはすたーすたー", "romaji": "watasiwasuta-suta-" },
  { "text": "あつあつあつあつ", "romaji": "atuatuatuatu" },
  { "text": "ちーむともだちちーむとも", "romaji": "ti-mutomodatiti-mutomo" },
  { "text": "かんさいかんとう", "romaji": "kannsaikannntou" },
  { "text": "いそがしくてねむれない", "romaji": "isogasikutenemurenai" },
  { "text": "じんせいげーむやりとく", "romaji": "jinnseige-muyaritoku" },
  { "text": "ぜんぶからぶりでしぬ", "romaji": "zennbukaraburidesinu" },
  { "text": "わたしはおわってる", "romaji": "watasiwaowatteru" },
  { "text": "むかつくだよそのかお", "romaji": "mukatikudayosonokao" },
  { "text": "わたしにくちづけを", "romaji": "watasinikutizukewo" },
  { "text": "かまってまってわたし", "romaji": "kamattematte-watasi" },
  { "text": "おつかれさまよいゆめを", "romaji": "otukaresamayoyiyumewo" },
  { "text": "めはあいとしれ", "romaji": "meawaaitosire" },
  { "text": "むねのなかあばれだす", "romaji": "munenonakaabaredasu" },
  { "text": "よるをあけたらしあわせ", "romaji": "yoruwoaketarasiawase" },
  { "text": "どこにもいけないよ", "romaji": "dokonimoyikenaiyo" },
  { "text": "きみはきみはきみは", "romaji": "kimihakimihakimih" },
  { "text": "あきぬほどねたいよ", "romaji": "akinuhodonetaiyo" },
  { "text": "えきのほーむあいにきた", "romaji": "ekinnoho-muainikita" },
  { "text": "でんしゃいぬいであいゆし", "romaji": "dennsyainuideaiyusi" },
  { "text": "つぎのえきはきみです", "romaji": "tuginnoekiwakimidesu" },
  { "text": "ほんまにうそじゃない", "romaji": "honmanniyusojanai" },
  { "text": "ずっときみとふざけたい", "romaji": "zuttokimitofuzaketai" },
  { "text": "たいようがみかたする", "romaji": "taiyougamikatasuru" },
  { "text": "あおぞらにいまさけびたい", "romaji": "aozoraniimasakebitai" },
  { "text": "きみをみてるだけでいい", "romaji": "kimiwomiterudakedeii" },
  { "text": "まほうつかいになれるかな", "romaji": "mahoutukaininarerukana" },
  { "text": "いっしょにたびをしよう", "romaji": "issyoniitabiwosiyou" },
  { "text": "じんせいはみじかいよ", "romaji": "jinnseiwaamijikaiyo" },
  { "text": "もっとしろうとおもった", "romaji": "mottosiroutoomotta" },
  { "text": "おもいではことばにしよう", "romaji": "omoidewakotobanisiyou" },
  { "text": "がんばったものはせんしだ", "romaji": "gannbattamonowasennsida" },
  { "text": "こわがることはわるくない", "romaji": "kowagarukotowawarukunai" },
  { "text": "このよにふかのうはない", "romaji": "konoyonifukanounai" },
  { "text": "ひとはどうでもいいことに", "romaji": "hitowadoudemo-iikotoni" },
  { "text": "いのちをかけないんだ", "romaji": "inotwiwokakenainnda" },
  { "text": "めだたずいきろ", "romaji": "medatazuikiro" },
  { "text": "あくしゅをしてわかれよう", "romaji": "akusyuwositewakareyou" },
  { "text": "きみのなまえをよんだよ", "romaji": "kiminonamaewoyonndayo" },
  { "text": "ぼくはきみのことしってる", "romaji": "bokuwakiminokotositteru" },
  { "text": "いどまきまきひいてひいて", "romaji": "itomakimakihiitehiite" },
  { "text": "とんとんとんとん", "romaji": "tonntonntonntonn" },
  { "text": "たまごっちおそろいだね", "romaji": "tamagottiosoroidane" },
  { "text": "にんてんどーみゅーじっく", "romaji": "ninntennndo-myu-jikku" },
  { "text": "てすとねぼうしたなう", "romaji": "tesutonebousitanau" },
  { "text": "じにんれぜだよわたし", "romaji": "jininnrezedayowatasi" },
  { "text": "かわいすぎてしぬうう", "romaji": "kawaisugitesinuuu" },
  { "text": "だんすむずかしくてしぬ", "romaji": "dannsumuzukasikutesinu" },
  { "text": "いれちがいぐっじょぶ", "romaji": "iretyigaigujjobu" },
  { "text": "きょうびじゅよすぎ", "romaji": "kyoubijuyosugi" },
  { "text": "ばらんがおになりたい", "romaji": "baranngaoninaritai" },
  { "text": "くにがおしんだんやろう", "romaji": "kunigaosinndannyarou" },
  { "text": "ぴぜやひとりのいのち", "romaji": "pizeyahitorinoinotwi" },
  { "text": "おれがぜったいたすける", "romaji": "oregazettaitasukeru" },
  { "text": "じゃまだよどいてくれ", "romaji": "jamadayodoitekure" },
  { "text": "ひとをすくうためならば", "romaji": "hitowosukuutamenaraba" },
  { "text": "るんちょまるんちょま", "romaji": "runntyomarunntyoma" },
  { "text": "まじでいってたそれ", "romaji": "majideittetadore" },
  { "text": "まじじあついよいま", "romaji": "majijiatiyoyoima" },
  { "text": "もうおそいよあつくなるの", "romaji": "mouosoiyoatukunaruno" },
  { "text": "ずっとあつかったよ", "romaji": "zuttoatukattayo" },
  { "text": "えぶらがいそがしい", "romaji": "eburagaisogasii" },
  { "text": "これまじなんすよ", "romaji": "koremajinnansuyo" },
  { "text": "いまのどうやったんですか", "romaji": "imanodouyattanndesuka" },
  { "text": "かみのははいしんおわり", "romaji": "kaminohaisinnowari" },
  { "text": "まりおよこでみながら", "romaji": "marioyokodeminnagara" },
  { "text": "ぼくだけはしがみつく", "romaji": "bokudakehasigamituku" },
  { "text": "ほそいほそいいとを", "romaji": "hosoyihosoyiyitowo" },
  { "text": "taguriyosetitunaide", "romaji": "taguriyosetitunaide" },
  { "text": "おれがせきにんをもつ", "romaji": "oregasekinninwomotu" },
  { "text": "げーむはじめるまでながい", "romaji": "ge-muhajimerumadenagai" },
  { "text": "ごじゅうかげつながくない", "romaji": "gojuukagetunagakunai" },
  { "text": "ばけもんだよあれは", "romaji": "bakemonndayoarewa" },
  { "text": "てすりひくすぎないですか", "romaji": "tesurihikusuginaidesuka" },
  { "text": "ろうかながすぎないですか", "romaji": "roukanagasuginaidesuka" },
  { "text": "びんかんなんだから", "romaji": "binnkannnanndakara" },
  { "text": "たいきあれてたよいいの", "romaji": "taikiaretetayoiino" },
  { "text": "れいぜいになれるから", "romaji": "reizeininarerukara" },
  { "text": "たすけてくださいよー", "romaji": "tasuketekudasaiyo-" },
  { "text": "こっちがぎゃんぐかな", "romaji": "kotigagyanngukana" },
  { "text": "だれかこれやばくない", "romaji": "darekakoreyabakunai" },
  { "text": "けいごとふつうのことば", "romaji": "keigotofutuunokotoba" },
  { "text": "はんはんではなすタイプ", "romaji": "hanhann-dehanasutaipu" },
  { "text": "よっちゃうときあります", "romaji": "yotyautokiarimasu" },
  { "text": "でんちゅうぶっこわした", "romaji": "denntyuubukkosita" },
  { "text": "みらんくんおこるかな", "romaji": "mirannkunnokorukana" },
  { "text": "onnsitugakawarimasune", "romaji": "onnsitugakawarimasune" },
  { "text": "げんそうのみらんくん", "romaji": "gennsounomirannkunn" },
  { "text": "きょくどのきょうふだね", "romaji": "kyokudonokyoufudane" },
  { "text": "めいおうにすんでそう", "romaji": "meiwounisunndesou" },
  { "text": "なまえだしていただく", "romaji": "namaedasiteidataku" },
  { "text": "じゅうにんにいくよ", "romaji": "juunninnniikuyo" },
  { "text": "にじさんじごりら", "romaji": "nijisannjigorira" },
  { "text": "にじさんじぷりんせす", "romaji": "nijisannjipurinnsesu" },
  { "text": "にじさんじきんぐ", "romaji": "nijisannjikinngu" },
  { "text": "おはこんるるー", "romaji": "ohakonnruru-" },
  { "text": "おつかれさまですしたー", "romaji": "otukaresamadesita-" },
  { "text": "またあしたあおうね", "romaji": "mataasitaaoune" },
  { "text": "いいなみおんてんね", "romaji": "iinamiottenne" },
  { "text": "あげみざわなう", "romaji": "agemizawanau" },
  { "text": "ないたーまじでないたー", "romaji": "naita-majidenaita-" },
  { "text": "くせがつよすぎる", "romaji": "kusegatuyosugiru" },
  { "text": "りあじゅうばくはつしろ", "romaji": "riajuubakuhatusiro" },
  { "text": "きみとのきおくわわすれない", "romaji": "kimitonokiokuwawasurenai" },
  { "text": "すぺしゃるさまきぬいて", "romaji": "supesyaruusamakinuite" },
  { "text": "なつにかけていくおもい", "romaji": "natunikaketeikuomoi" },
  { "text": "ゆうなぎにのっている", "romaji": "yuunaginiootteiru" },
  { "text": "まじっくはいらないよ", "romaji": "majikkuhayiranaiyo" },
  { "text": "とくべつにしてほしい", "romaji": "tokubetunisitihosii" },
  { "text": "らぶじゃたりないよ", "romaji": "rabujatarinaiyo" },
  { "text": "いちばんうつくしいすうじ", "romaji": "itibannutukusiisuuji" },
  { "text": "おもいでのほうこう", "romaji": "omoidenohoukou" },
  { "text": "ほほこりがひかってみえる", "romaji": "hokorigahikattemieru" },
  { "text": "ばいまいふさいれんと", "romaji": "baimaifusairennto" },
  { "text": "かんぜんちたいになろう", "romaji": "kannzentiitaininarou" },
  { "text": "さんばんほーむじゅんきゅう", "romaji": "sannbannho-mujunkyuu" },
  { "text": "らいらきみもまつよ", "romaji": "rairakimimomatuyo" },
  { "text": "じんせいのきずもいとしく", "romaji": "jinnseinokizumoitosiku" },
  { "text": "わすれてしまうぼくら", "romaji": "wasuretesimaubokura" },
  { "text": "ひみつだけはあいしてる", "romaji": "himitudakewaaiteru" },
  { "text": "うそでつつむきゃりあ", "romaji": "usodetutumuakyaria" },
  { "text": "きれいなわるをかくした", "romaji": "kireinawaruwokakusita" },
  { "text": "わたしなりのあいだよ", "romaji": "watasinarinoaidayo" },
  { "text": "あのーこはとくべつです", "romaji": "ano-kowatokubetudesu" },
  { "text": "われわれはまけです", "romaji": "warewarewamanekedesu" },
  { "text": "おしさまのひきたてやく", "romaji": "osisamanohikitateyaku" },
  { "text": "さいきょうでむてきのあい", "romaji": "saikyoudemutekinoai" },
  { "text": "てんさいてきなあいどる", "romaji": "tensaitekinaaidoru" },
  { "text": "むかつくだよそのかお", "romaji": "mukatikudayosonokao" },
  { "text": "なれたせりふでじゃすと", "romaji": "naretaserifudejasuto" },
  { "text": "わたしのくちぐせだよ", "romaji": "watasinokutigusedayo" },
  { "text": "がんばってわたしに", "romaji": "gannbattewatasi" },
  { "text": "かまってまってわたしだけ", "romaji": "kamattematte-watasidake" },
  { "text": "おつかれさまよいゆめを", "romaji": "otukaresamayoyiyumewo" },
  { "text": "いまさらむねのなか", "romaji": "imasaramunenonaka" },
  { "text": "あのーこはもうゆれのなか", "romaji": "ano-kowamouyurenonaka" },
  { "text": "よるをあけたらまよう", "romaji": "yoruwoaketaramayou" },
  { "text": "なにかこがよるこえたら", "romaji": "nanikakogayorukoetara" },
  { "text": "しあわせになれるだろう", "romaji": "siawaseninarerudarou" },
  { "text": "なんだったんだろうね", "romaji": "nannndattanndaroune" },
  { "text": "じぶんでかえるのへや", "romaji": "jibunndekaerunoheya" },
  { "text": "えきのにほーむまたきた", "romaji": "ekinoho-mumatakita" },
  { "text": "でんきりあいにきたよ", "romaji": "dennkiriainikitayo" },
  { "text": "きみのまちのでんしゃ", "romaji": "kiminomatinodennsya" },
  { "text": "とまらないよまたあいに", "romaji": "tomaranaiyomataaini" },
  { "text": "きみのひとづめこんで", "romaji": "kiminohitodumekonnde" },
  { "text": "はぴてぃきみのむね", "romaji": "hapititkiminomune" },
  { "text": "だきしめたさないで", "romaji": "dakisimetasanaide" },
  { "text": "ずっときみとふざけたい", "romaji": "zuttokimitofuzaketai" },
  { "text": "きみのえくすぷれす", "romaji": "kiminoekusupuresu" },
  { "text": "たいようがみかたするひ", "romaji": "taiyougamikatasuruhi" },
  { "text": "きたいしてるんだよね", "romaji": "kitaisiterunndayone" },
  { "text": "やくそくのきせつにいく", "romaji": "yakusokunokisetuniiku" },
  { "text": "にんぎょうみたいだね", "romaji": "ninngyoumitaidane" },
  { "text": "ほうしゃのつみにひかり", "romaji": "housyanotuminihikari" },
  { "text": "てれてばかりじゃんか", "romaji": "teretebakarijannka" },
  { "text": "あおぞらにいまさけぶよ", "romaji": "aozoraniimasakebuyo" },
  { "text": "きみをあもっているよ", "romaji": "kimiwoamotteiruyo" },
  { "text": "ぎりぎりはっぴーなう", "romaji": "girigirihappi-nau" },
  { "text": "まじでばいとだりい", "romaji": "majidebaitodarii" },
  { "text": "たいちょうわるすぎる", "romaji": "taityouwarusugiru" },
  { "text": "やすみのれんらくする", "romaji": "yasuminorennrakusuru" },
  { "text": "べっどでだらだらじごく", "romaji": "beddodedaradarajigoku" },
  { "text": "ねこのじゅうごじはん", "romaji": "nekonojuugojihann" },
  { "text": "じかんをかけようね", "romaji": "jikannwokakeyoune" },
  { "text": "うしろからひびくよ", "romaji": "usirokarahibikuyo" },
  { "text": "かちかちこおったはが", "romaji": "katikatikoottahaga" },
  { "text": "ねっこがあるいてるよ", "romaji": "nekkogaaruiteruyo" },
  { "text": "うちらころかわいすぎ", "romaji": "utirakorokawaisugi" },
  { "text": "しらんけどまじしらん", "romaji": "sirannkedomajisirann" },
  { "text": "きょうびじゅいいじゃん", "romaji": "kyoubijuiijan" },
  { "text": "ここわどころしあだっけ", "romaji": "kokowadokorosiodakke" },
  { "text": "びざがないといだされた", "romaji": "bizagannaitoidasareta" },
  { "text": "りざじゃないりざだよ", "romaji": "rizajanairizadayo" },
  { "text": "かなしくてないていたよ", "romaji": "kanasikutenaiteitayo" },
  { "text": "ひとりであるくかえりみち", "romaji": "hitoridearukukaerimiti" },
  { "text": "こわいなみんなにあいたい", "romaji": "kowainaminnanniaitai" },
  { "text": "あいされたいされたい", "romaji": "aisaretaisaretai" },
  { "text": "あかぬけてりべんじなう", "romaji": "akanuketeribenjinau" },
  { "text": "ぬまらせたいらせたい", "romaji": "numarasetaisetai" },
  { "text": "よそみできないくらい", "romaji": "yosomidekinaikurai" },
  { "text": "きみにふられてさいじょう", "romaji": "kiminifuraterusaijou" },
  { "text": "じぶんがいちばんときめく", "romaji": "jibunngaityibanntokimeku" },
  { "text": "みとめないよおとめのぎゃく", "romaji": "mitomenaiyootomenogyaku" },
  { "text": "おかねかせぐおれたち", "romaji": "okanekaseguoretati" },
  { "text": "わたしはすたーすたー", "romaji": "watasiwasuta-suta-" },
  { "text": "きらきらわたしはすたー", "romaji": "kirakirawatasiwasuta-" },
  { "text": "あはあはあはあは", "romaji": "ahaahaahaaha" },
  { "text": "ちーむともだちだよ", "romaji": "ti-mutomodatidayo" },
  { "text": "おれたちなにちーむともだち", "romaji": "oretatinaniti-mutomodati" },
  { "text": "かんさいかんとうにしひがし", "romaji": "kannsaikannntounisihigasi" },
  { "text": "いそがしくてねむれないわ", "romaji": "isogasikutenemurenaiwa" },
  { "text": "だれかきぜつさせてくれ", "romaji": "darekakizetusasitekure" },
  { "text": "じんせいげーむやりとく", "romaji": "jinnseige-muyaritoku" },
  { "text": "わたしがわるいんだよ", "romaji": "watasigawaruinndayo" },
  { "text": "ほんきでやってもぜんぶ", "romaji": "honnikideyaattemozenbu" },
  { "text": "からぶりでしらないくせに", "romaji": "karaburidesiranaikuseni" },
  { "text": "わたしはおわってるなう", "romaji": "watasiwaowatterunau" }
];

const WORDS_CONVERSATION: WordDefinition[] = [
  { "text": "こんにちは", "romaji": "KONNICHIWA" }, { "text": "おはよう", "romaji": "OHAYOU" },
  { "text": "こんばんは", "romaji": "KONBANWA" }, { "text": "おやすみ", "romaji": "OYASUMI" },
  { "text": "ありがとう", "romaji": "ARIGATOU" }, { "text": "ごめんね", "romaji": "GOMENNE" },
  { "text": "すみません", "romaji": "SUMIMASEN" }, { "text": "さようなら", "romaji": "SAYOUNARA" },
  { "text": "またね", "romaji": "MATANE" }, { "text": "ばいばい", "romaji": "BAIBAI" },
  { "text": "よろしく", "romaji": "YOROSHIKU" }, { "text": "はじめまして", "romaji": "HAJIMEMASHITE" },
  { "text": "おひさしぶり", "romaji": "OHISASHIBURI" }, { "text": "げんき", "romaji": "GENKI" },
  { "text": "いいよ", "romaji": "IIYO" }, { "text": "だめだよ", "romaji": "DAMEDAYO" },
  { "text": "おっけー", "romaji": "OKKE-" }, { "text": "わかった", "romaji": "WAKATTA" },
  { "text": "しらない", "romaji": "SHIRANAI" }, { "text": "そうなんだ", "romaji": "SOUNANDA" },
  { "text": "ほんとう", "romaji": "HONTOU" }, { "text": "うそでしょ", "romaji": "USODESHO" },
  { "text": "まじで", "romaji": "MAJIDE" }, { "text": "すごいね", "romaji": "SUGOINE" },
  { "text": "さすが", "romaji": "SASUGA" }, { "text": "やったー", "romaji": "YATTA-" },
  { "text": "うれしい", "romaji": "URESHII" }, { "text": "たのしい", "romaji": "TANOSHII" },
  { "text": "かなしい", "romaji": "KANASHII" }, { "text": "おもしろい", "romaji": "OMOSHIROI" },
  { "text": "つまらない", "romaji": "TSUMARANAI" }, { "text": "むずかしい", "romaji": "MUZUKASHII" },
  { "text": "かんたん", "romaji": "KANTAN" }, { "text": "がんばれ", "romaji": "GANBARE" },
  { "text": "ふぁいと", "romaji": "FAITO" }, { "text": "おつかれ", "romaji": "OTSUKARE" },
  { "text": "どんまい", "romaji": "DONMAI" }, { "text": "きにしないで", "romaji": "KINISHINAIDE" },
  { "text": "だいじょうぶ", "romaji": "DAIJOUBU" }, { "text": "たすけて", "romaji": "TASUKETE" },
  { "text": "てつだって", "romaji": "TETSUDATTE" }, { "text": "いただきまーす", "romaji": "ITADAKIMA-SU" },
  { "text": "ごちそうさま", "romaji": "GOCHISOUSAMA" }, { "text": "いってきます", "romaji": "ITTEKIMASU" },
  { "text": "いってらっしゃい", "romaji": "ITTERASSHAI" }, { "text": "ただいま", "romaji": "TADAIMA" },
  { "text": "おかえり", "romaji": "OKAERI" }, { "text": "おめでとう", "romaji": "OMEDETOU" },
  { "text": "あけおめ", "romaji": "AKEOME" }, { "text": "ことよろ", "romaji": "KOTOYORO" },
  { "text": "それな", "romaji": "SORENA" }, { "text": "わかりみ", "romaji": "WAKARIMI" },
  { "text": "すき", "romaji": "SUKI" }, { "text": "きらい", "romaji": "KIRAI" },
  { "text": "おし", "romaji": "OSHI" }, { "text": "とうとい", "romaji": "TOUTOI" },
  { "text": "かみ", "romaji": "KAMI" }, { "text": "てんし", "romaji": "TENSHI" },
  { "text": "くさ", "romaji": "KUSA" }, { "text": "わろた", "romaji": "WAROTA" },
  { "text": "りょ", "romaji": "RYO" }, { "text": "はあ", "romaji": "HAA" },
  { "text": "なぞ", "romaji": "NAZO" }, { "text": "えぐい", "romaji": "EGUI" },
  { "text": "やばい", "romaji": "YABAI" }, { "text": "ぴえん", "romaji": "PIEN" },
  { "text": "ぱおん", "romaji": "PAON" }, { "text": "しかたん", "romaji": "SHIKATAN" },
  { "text": "うける", "romaji": "UKERU" }, { "text": "つらい", "romaji": "TSURAI" },
  { "text": "ねむい", "romaji": "NEMUI" }, { "text": "ひま", "romaji": "HIMA" },
  { "text": "なにしてるの", "romaji": "NANISHITERUNO" }, { "text": "どこいくの", "romaji": "DOKOIKUNO" },
  { "text": "いつあう", "romaji": "ITSUAU" }, { "text": "まちあわせ", "romaji": "MACHIAWASE" },
  { "text": "ちこく", "romaji": "CHIKOKU" }, { "text": "いそいで", "romaji": "ISOIDE" },
  { "text": "ゆっくりでいいよ", "romaji": "YUKKURIDEIIYO" }, { "text": "きをつけて", "romaji": "KIWOTSUKETE" },
  { "text": "またあとで", "romaji": "MATAATODE" }, { "text": "れんらくして", "romaji": "RENRAKUSHITE" },
  { "text": "でんわして", "romaji": "DENWASHITE" }, { "text": "らいんして", "romaji": "RAINSHITE" },
  { "text": "しゃしんとって", "romaji": "SHASHINTOTTE" }, { "text": "いんすたばえ", "romaji": "INSUTABAE" },
  { "text": "いいかんじ", "romaji": "IIKANJI" }, { "text": "びみょう", "romaji": "BIMYOU" },
  { "text": "さいこう", "romaji": "SAIKOU" }, { "text": "さいてい", "romaji": "SAITEI" },
  { "text": "まさか", "romaji": "MASAKA" }, { "text": "やっぱり", "romaji": "YAPPARI" },
  { "text": "なるほど", "romaji": "NARUHODO" }, { "text": "たしかに", "romaji": "TASHIKANI" },
  { "text": "おなかすいた", "romaji": "ONAKASUITA" }, { "text": "のどかわいた", "romaji": "NODOKAWAITA" },
  { "text": "といれ", "romaji": "TOIRE" }, { "text": "といれいきたい", "romaji": "TOIREIKITAI" },
  { "text": "わんちゃん", "romaji": "WANCHAN" }, { "text": "しらんけど", "romaji": "SHIRANKEDO" },
  { "text": "がち", "romaji": "GACHI" }, { "text": "めっちゃ", "romaji": "MECCHA" },
  { "text": "きまず", "romaji": "KIMAZU" }, { "text": "つんだ", "romaji": "TSUNDA" },
  { "text": "むり", "romaji": "MURI" }, { "text": "しんどい", "romaji": "SHINDOI" },
  { "text": "えもい", "romaji": "EMOI" }, { "text": "ちる", "romaji": "CHIRU" },
  { "text": "ささる", "romaji": "SASARU" }, { "text": "ぬま", "romaji": "NUMA" },
  { "text": "おしかつ", "romaji": "OSHIKATSU" }, { "text": "ふぁぼ", "romaji": "FABO" },
  { "text": "りぷ", "romaji": "RIPU" }, { "text": "すぱちゃ", "romaji": "SUPACHA" },
  { "text": "あか", "romaji": "AKA" }, { "text": "うらあか", "romaji": "URAAKA" },
  { "text": "ほんあか", "romaji": "HONAKA" }, { "text": "かぎあか", "romaji": "KAGIAKA" },
  { "text": "さぶあか", "romaji": "SABUAKA" }, { "text": "たいむらいん", "romaji": "TAIMURAIN" },
  { "text": "すとおりー", "romaji": "SUTOORI-" }, { "text": "いんすた", "romaji": "INSUTA" },
  { "text": "てぃっくとっく", "romaji": "TIKKUTOKKU" }, { "text": "えんじょう", "romaji": "ENJOU" },
  { "text": "めんへら", "romaji": "MENHERA" }, { "text": "じらい", "romaji": "JIRAI" },
  { "text": "りある", "romaji": "RIARU" }, { "text": "りあじゅう", "romaji": "RIAJUU" },
  { "text": "いんきゃ", "romaji": "INKYA" }, { "text": "ようきゃ", "romaji": "YOUKYA" },
  { "text": "ぼっち", "romaji": "BOCCHI" }, { "text": "ぱりぴ", "romaji": "PARIPI" },
  { "text": "ぎゃる", "romaji": "GYARU" }, { "text": "こみゅしょう", "romaji": "KOMYUSHOU" },
  { "text": "めしてろ", "romaji": "MESHITERO" }, { "text": "すたりば", "romaji": "SUTARIBA" },
  { "text": "べんきょう", "romaji": "BENKYOU" }, { "text": "かこもん", "romaji": "KAKOMON" },
  { "text": "ふるたん", "romaji": "FURUTAN" }, { "text": "らくたん", "romaji": "RAKUTAN" },
  { "text": "きゅうこう", "romaji": "KYUUKOU" }, { "text": "さぼり", "romaji": "SABORI" },
  { "text": "ねぼう", "romaji": "NEBOU" }, { "text": "おーる", "romaji": "O-RU" },
  { "text": "からおけ", "romaji": "KARAOKE" }, { "text": "ひとから", "romaji": "HITOKARA" },
  { "text": "たぴおか", "romaji": "TAPIOKA" }, { "text": "すたば", "romaji": "SUTABA" },
  { "text": "まっく", "romaji": "MAKKU" }, { "text": "さいぜ", "romaji": "SAIZE" },
  { "text": "ぷりくら", "romaji": "PURIKURA" }, { "text": "もる", "romaji": "MORU" },
  { "text": "かこう", "romaji": "KAKOU" }, { "text": "すっぴん", "romaji": "SUPPIN" },
  { "text": "めいく", "romaji": "MEIKU" }, { "text": "ふぁっしょん", "romaji": "FASSHON" },
  { "text": "こーで", "romaji": "KO-DE" }, { "text": "ださい", "romaji": "DASAI" },
  { "text": "おしゃれ", "romaji": "OSHARE" }, { "text": "いけてる", "romaji": "IKETERU" },
  { "text": "いけめん", "romaji": "IKEMEN" }, { "text": "いけぼ", "romaji": "IKEBO" },
  { "text": "かわぼ", "romaji": "KAWABO" }, { "text": "きゅんです", "romaji": "KYUNDESU" },
  { "text": "はにゃ", "romaji": "HANYA" }, { "text": "ひよってる", "romaji": "HIYOTTERU" },
  { "text": "だいじょうぶそ", "romaji": "DAIJOUBUSO" }, { "text": "してもろて", "romaji": "SHITEMOROTE" },
  { "text": "あせあせ", "romaji": "ASEASE" }, { "text": "うぇーい", "romaji": "WE-I" },
  { "text": "けーぴー", "romaji": "KE-PI-" }, { "text": "かんぱい", "romaji": "KANPAI" },
  { "text": "おつ", "romaji": "OTSU" }, { "text": "うぽつ", "romaji": "UPOTSU" },
  { "text": "ぱちぱちぱち", "romaji": "PACHIPACHIPACHI" }, { "text": "わら", "romaji": "WARA" },
  { "text": "むりみ", "romaji": "MURIMI" }, { "text": "ふかい", "romaji": "FUKAI" },
  { "text": "いみわからん", "romaji": "IMIWAKARAN" }, { "text": "かみたいおう", "romaji": "KAMITAIOU" },
  { "text": "しおたいおう", "romaji": "SHIOTAIOU" }, { "text": "めんどい", "romaji": "MENDOI" },
  { "text": "だるい", "romaji": "DARUI" }, { "text": "かまちょ", "romaji": "KAMACHO" },
  { "text": "きどく", "romaji": "KIDOKU" }, { "text": "みどく", "romaji": "MIDOKU" },
  { "text": "ぶろ", "romaji": "BURO" }, { "text": "めっせ", "romaji": "MESSE" },
  { "text": "つうわ", "romaji": "TSUUWA" }, { "text": "びビデオ", "romaji": "BIDEO" },
  { "text": "すくしょ", "romaji": "SUKUSHO" }, { "text": "がぞう", "romaji": "GAZOU" },
  { "text": "りんく", "romaji": "RINKU" }, { "text": "しょうたい", "romaji": "SHOUTAI" },
  { "text": "ぐるーぷ", "romaji": "GURU-PU" }, { "text": "のーぷらん", "romaji": "NO-PURAN" },
  { "text": "ふっかる", "romaji": "FUKKARU" }, { "text": "のみかい", "romaji": "NOMIKAI" },
  { "text": "おはよう", "romaji": "ohayou" },
  { "text": "おやすみ", "romaji": "oyasumi" },
  { "text": "おつかれ", "romaji": "otukare" },
  { "text": "またね", "romaji": "matane" },
  { "text": "よろしく", "romaji": "yorosiku" },
  { "text": "ありがとう", "romaji": "arigatou" },
  { "text": "ごめんね", "romaji": "gomenne" },
  { "text": "おっけー", "romaji": "okke-" },
  { "text": "りょかい", "romaji": "ryokai" },
  { "text": "それな", "romaji": "sorena" },
  { "text": "まじで", "romaji": "majide" },
  { "text": "やばい", "romaji": "yabai" },
  { "text": "がちで", "romaji": "gatide" },
  { "text": "ほんまに", "romaji": "honmani" },
  { "text": "わかる", "romaji": "wakaru" },
  { "text": "うける", "romaji": "ukeru" },
  { "text": "しぬ", "romaji": "sinu" },
  { "text": "くさ", "romaji": "kusa" },
  { "text": "わら", "romaji": "wara" },
  { "text": "きまずい", "romaji": "kimazui" },
  { "text": "えぐい", "romaji": "egui" },
  { "text": "つら", "romaji": "tura" },
  { "text": "むり", "romaji": "muri" },
  { "text": "きもい", "romaji": "kimoi" },
  { "text": "すごい", "romaji": "sugoi" },
  { "text": "さいこう", "romaji": "saikou" },
  { "text": "てんさい", "romaji": "tensai" },
  { "text": "かみ", "romaji": "kami" },
  { "text": "とうとい", "romaji": "toutoi" },
  { "text": "しんどい", "romaji": "sindoi" },
  { "text": "あざまる", "romaji": "azamaru" },
  { "text": "おけまる", "romaji": "okemaru" },
  { "text": "りょ", "romaji": "ryo" },
  { "text": "ぱおん", "romaji": "paonn" },
  { "text": "ぴえん", "romaji": "pienn" },
  { "text": "きびしいって", "romaji": "kibisiitte" },
  { "text": "ききかん", "romaji": "kikikann" },
  { "text": "それがーちゃー", "romaji": "sorega-tya-" },
  { "text": "びじゅいい", "romaji": "bijuii" },
  { "text": "めろい", "romaji": "meroi" },
  { "text": "きゃぱい", "romaji": "kyapai" },
  { "text": "ちゅき", "romaji": "tyuki" },
  { "text": "わんちゃん", "romaji": "wantyann" },
  { "text": "ありよりのあり", "romaji": "ariyorinoari" },
  { "text": "なしよりのなし", "romaji": "nasiyorinonasi" },
  { "text": "しらんけど", "romaji": "sirankedo" },
  { "text": "いうて", "romaji": "iyute" },
  { "text": "ぶっちゃけ", "romaji": "buttyake" },
  { "text": "てかさ", "romaji": "tekasa" },
  { "text": "あざーす", "romaji": "aza-su" },
  { "text": "おつおつ", "romaji": "otuotu" },
  { "text": "まじそれな", "romaji": "majisorena" },
  { "text": "それなすぎる", "romaji": "sorenasugiru" },
  { "text": "ほんまそれ", "romaji": "honmasore" },
  { "text": "おはよ", "romaji": "ohayo" },
  { "text": "おやす", "romaji": "oyasu" },
  { "text": "おつ", "romaji": "otu" },
  { "text": "りょー", "romaji": "ryo-" },
  { "text": "おけー", "romaji": "oke-" },
  { "text": "まじー", "romaji": "maji-" },
  { "text": "やばー", "romaji": "yaba-" },
  { "text": "がちー", "romaji": "gati-" },
  { "text": "ほんまー", "romaji": "honma-" },
  { "text": "わらー", "romaji": "wara-" },
  { "text": "きまずー", "romaji": "kimazu-" },
  { "text": "えぐー", "romaji": "egu-" },
  { "text": "つらー", "romaji": "tura-" },
  { "text": "むりー", "romaji": "muri-" },
  { "text": "すごいー", "romaji": "sugoi-" },
  { "text": "さいこー", "romaji": "saiko-" },
  { "text": "かみー", "romaji": "kami-" },
  { "text": "とうといー", "romaji": "toutoi-" },
  { "text": "あざー", "romaji": "aza-" },
  { "text": "きびしー", "romaji": "kibisi-" },
  { "text": "わかんのー", "romaji": "wakanno-" },
  { "text": "えっほー", "romaji": "ehho-" },
  { "text": "ちゃーん", "romaji": "tya-nn" },
  { "text": "けーぴー", "romaji": "ke-pi-" },
  { "text": "ぴーえー", "romaji": "pi-e-" },
  { "text": "なう", "romaji": "nau" },
  { "text": "わず", "romaji": "wazu" },
  { "text": "うぃる", "romaji": "wiru" },
  { "text": "おわこん", "romaji": "owakonn" },
  { "text": "かまちょ", "romaji": "kamatyo" },
  { "text": "かまてん", "romaji": "kamatenn" },
  { "text": "とりま", "romaji": "torima" },
  { "text": "ぱりぴ", "romaji": "paripi" },
  { "text": "りある", "romaji": "riaru" },
  { "text": "わこつ", "romaji": "wakotu" },
  { "text": "おつん", "romaji": "otunn" },
  { "text": "よろ", "romaji": "yoro" },
  { "text": "おめ", "romaji": "ome" },
  { "text": "おたおめ" , "romaji": "otaome" },
  { "text": "よろしくねー", "romaji": "yorosikune-" },
  { "text": "おつかれさま", "romaji": "otukaresama" },
  { "text": "またねー", "romaji": "matane-" },
  { "text": "ばいばい", "romaji": "baibai" },
  { "text": "はーい", "romaji": "ha-i" },
  { "text": "ほなね", "romaji": "honane" }
];

export const getWordsByDifficulty = (difficulty: Difficulty): WordDefinition[] => {
  switch (difficulty) {
    case Difficulty.EASY: return CHARS_EASY;
    case Difficulty.NORMAL: return WORDS_NORMAL;
    case Difficulty.HARD: return WORDS_HARD;
    case Difficulty.MASTER: return WORDS_MASTER;
    case Difficulty.CONVERSATION: return WORDS_CONVERSATION;
    default: return CHARS_EASY;
  }
};